#compact: true
#quiet: true
download-external-modules: true
external-modules-download-path: .external_modules
framework: all
evaluate-variables: true
skip-path: cdk/cdk.out/asset.*
skip-check: CKV_AWS_117
