# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.9
default_stages:
  - commit
  - push
fail_fast: False
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  - id: check-added-large-files
  - id: check-docstring-first
  - id: check-symlinks
  - id: debug-statements
  - id: detect-aws-credentials
    args:
      - --allow-missing-credentials
  - id: detect-private-key
  - id: no-commit-to-branch
    name: no-commit-to-master
    args:
      - --branch
      - master
  - id: no-commit-to-branch
    name: no-commit-to-main
    args:
      - --branch
      - main
  - id: mixed-line-ending
    args: [ --fix=lf ]
  - id: requirements-txt-fixer
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies:
        - mccabe==0.6.1
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.15.1
  hooks:
  - id: gitlint
    stages: [commit-msg]
- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
  - id: add-trailing-comma
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.3
  hooks:
  - id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort
    additional_dependencies: [toml]
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
    language_version: python3.9
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
    - id: pydocstyle
      additional_dependencies:
        - toml
- repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  rev: v1.0.5
  hooks:
    - id: python-bandit-vulnerability-check
      args: [--ini, .banditrc, --recursive, modules, --exclude, "*/.external_modules/*,*/.terraform/*"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.910'
  hooks:
    - id: mypy
      additional_dependencies: [types-requests]
      args: [--strict, --ignore-missing-imports, --allow-untyped-decorators, --install-types, --non-interactive]
- repo: local
  hooks:
  - id: security-scanning
    name: checkov
    entry: bash -c 'cd cdk && cdk synth > /dev/null && cd .. && checkov -d .'
    language: system
    pass_filenames: false
